// <auto-generated />
using System;
using GarageLog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarageLog.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810202041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarageLog.Core.Entities.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSelfService")
                        .HasColumnType("boolean")
                        .HasColumnName("is_self_service");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<string>("ShopName")
                        .HasColumnType("text")
                        .HasColumnName("shop_name");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_cost");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_service_records");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_service_records_vehicle_id");

                    b.ToTable("service_records", (string)null);
                });

            modelBuilder.Entity("GarageLog.Core.Entities.ServiceRecordItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomName")
                        .HasColumnType("text")
                        .HasColumnName("custom_name");

                    b.Property<int>("ServiceRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("service_record_id");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    b.HasKey("Id")
                        .HasName("pk_service_record_items");

                    b.HasIndex("ServiceRecordId")
                        .HasDatabaseName("ix_service_record_items_service_record_id");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_service_record_items_service_type_id");

                    b.ToTable("service_record_items", (string)null);
                });

            modelBuilder.Entity("GarageLog.Core.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_service_types");

                    b.ToTable("service_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Engine",
                            Name = "Oil Change"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tires",
                            Name = "Tire Rotation"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Brakes",
                            Name = "Brake Pad Replacement"
                        },
                        new
                        {
                            Id = 1000,
                            Category = "Body & Frame",
                            Name = "Body Inspected"
                        },
                        new
                        {
                            Id = 1001,
                            Category = "Body & Frame",
                            Name = "Front Body Inspected"
                        },
                        new
                        {
                            Id = 1002,
                            Category = "Body & Frame",
                            Name = "Rear Body Inspected"
                        },
                        new
                        {
                            Id = 1003,
                            Category = "Body & Frame",
                            Name = "Front Paint Inspected"
                        },
                        new
                        {
                            Id = 1004,
                            Category = "Body & Frame",
                            Name = "Rear Paint Inspected"
                        },
                        new
                        {
                            Id = 1005,
                            Category = "Body & Frame",
                            Name = "Scratch Repaired"
                        },
                        new
                        {
                            Id = 1006,
                            Category = "Body & Frame",
                            Name = "Dent Repaired"
                        },
                        new
                        {
                            Id = 1007,
                            Category = "Body & Frame",
                            Name = "Rust Inspected"
                        },
                        new
                        {
                            Id = 1008,
                            Category = "Body & Frame",
                            Name = "Rust Repaired"
                        },
                        new
                        {
                            Id = 1009,
                            Category = "Body & Frame",
                            Name = "Underbody Inspected"
                        },
                        new
                        {
                            Id = 1010,
                            Category = "Body & Frame",
                            Name = "Undercoating Applied"
                        },
                        new
                        {
                            Id = 1011,
                            Category = "Body & Frame",
                            Name = "Door Hinges Lubricated"
                        },
                        new
                        {
                            Id = 1012,
                            Category = "Body & Frame",
                            Name = "Door Lock Repaired"
                        },
                        new
                        {
                            Id = 1013,
                            Category = "Body & Frame",
                            Name = "Window Regulator Replaced"
                        },
                        new
                        {
                            Id = 1014,
                            Category = "Body & Frame",
                            Name = "Weather Strip Replaced"
                        },
                        new
                        {
                            Id = 1015,
                            Category = "Body & Frame",
                            Name = "Windshield Repaired"
                        },
                        new
                        {
                            Id = 1016,
                            Category = "Body & Frame",
                            Name = "Windshield Replaced"
                        },
                        new
                        {
                            Id = 1017,
                            Category = "Body & Frame",
                            Name = "Wiper Blades Replaced"
                        },
                        new
                        {
                            Id = 1018,
                            Category = "Body & Frame",
                            Name = "Side Mirror Replaced"
                        },
                        new
                        {
                            Id = 1019,
                            Category = "Body & Frame",
                            Name = "Hood Latch Serviced"
                        },
                        new
                        {
                            Id = 1020,
                            Category = "Body & Frame",
                            Name = "Trunk Latch Serviced"
                        },
                        new
                        {
                            Id = 3000,
                            Category = "Brakes",
                            Name = "Brake System Inspected"
                        },
                        new
                        {
                            Id = 3001,
                            Category = "Brakes",
                            Name = "Front Brake Pads Replaced"
                        },
                        new
                        {
                            Id = 3002,
                            Category = "Brakes",
                            Name = "Rear Brake Pads Replaced"
                        },
                        new
                        {
                            Id = 3003,
                            Category = "Brakes",
                            Name = "Front Brake Rotors Replaced"
                        },
                        new
                        {
                            Id = 3004,
                            Category = "Brakes",
                            Name = "Rear Brake Rotors Replaced"
                        },
                        new
                        {
                            Id = 3005,
                            Category = "Brakes",
                            Name = "Front Brake Rotors Resurfaced"
                        },
                        new
                        {
                            Id = 3006,
                            Category = "Brakes",
                            Name = "Rear Brake Rotors Resurfaced"
                        },
                        new
                        {
                            Id = 3007,
                            Category = "Brakes",
                            Name = "Brake Fluid Flushed"
                        },
                        new
                        {
                            Id = 3008,
                            Category = "Brakes",
                            Name = "Brake Lines Repaired"
                        },
                        new
                        {
                            Id = 3009,
                            Category = "Brakes",
                            Name = "Front Brake Hoses Replaced"
                        },
                        new
                        {
                            Id = 3010,
                            Category = "Brakes",
                            Name = "Rear Brake Hoses Replaced"
                        },
                        new
                        {
                            Id = 3011,
                            Category = "Brakes",
                            Name = "Front Brake Calipers Replaced"
                        },
                        new
                        {
                            Id = 3012,
                            Category = "Brakes",
                            Name = "Rear Brake Calipers Replaced"
                        },
                        new
                        {
                            Id = 3013,
                            Category = "Brakes",
                            Name = "Parking Brake Adjusted"
                        },
                        new
                        {
                            Id = 3014,
                            Category = "Brakes",
                            Name = "Parking Brake Serviced"
                        },
                        new
                        {
                            Id = 3015,
                            Category = "Brakes",
                            Name = "ABS System Inspected"
                        },
                        new
                        {
                            Id = 3016,
                            Category = "Brakes",
                            Name = "Front ABS Sensor Replaced"
                        },
                        new
                        {
                            Id = 3017,
                            Category = "Brakes",
                            Name = "Rear ABS Sensor Replaced"
                        },
                        new
                        {
                            Id = 5000,
                            Category = "Electrical",
                            Name = "Battery Inspected"
                        },
                        new
                        {
                            Id = 5001,
                            Category = "Electrical",
                            Name = "Battery Replaced"
                        },
                        new
                        {
                            Id = 5002,
                            Category = "Electrical",
                            Name = "Battery Terminals Cleaned"
                        },
                        new
                        {
                            Id = 5003,
                            Category = "Electrical",
                            Name = "Battery Cables Replaced"
                        },
                        new
                        {
                            Id = 5004,
                            Category = "Electrical",
                            Name = "Charging System Tested"
                        },
                        new
                        {
                            Id = 5005,
                            Category = "Electrical",
                            Name = "Alternator Replaced"
                        },
                        new
                        {
                            Id = 5006,
                            Category = "Electrical",
                            Name = "Starter Replaced"
                        },
                        new
                        {
                            Id = 5007,
                            Category = "Electrical",
                            Name = "Fuses Replaced"
                        },
                        new
                        {
                            Id = 5008,
                            Category = "Electrical",
                            Name = "Relays Replaced"
                        },
                        new
                        {
                            Id = 5009,
                            Category = "Electrical",
                            Name = "Wiring Repaired"
                        },
                        new
                        {
                            Id = 5010,
                            Category = "Electrical",
                            Name = "Electrical System Diagnosed"
                        },
                        new
                        {
                            Id = 5011,
                            Category = "Electrical",
                            Name = "Headlights Replaced"
                        },
                        new
                        {
                            Id = 5012,
                            Category = "Electrical",
                            Name = "Tail Lights Replaced"
                        },
                        new
                        {
                            Id = 5013,
                            Category = "Electrical",
                            Name = "Bulbs Replaced"
                        },
                        new
                        {
                            Id = 5014,
                            Category = "Electrical",
                            Name = "ECU Diagnosed"
                        },
                        new
                        {
                            Id = 5015,
                            Category = "Electrical",
                            Name = "Software Updated"
                        },
                        new
                        {
                            Id = 5016,
                            Category = "Electrical",
                            Name = "Key Fob Battery Replaced"
                        },
                        new
                        {
                            Id = 7000,
                            Category = "HVAC",
                            Name = "HVAC System Inspected"
                        },
                        new
                        {
                            Id = 7001,
                            Category = "HVAC",
                            Name = "Cabin Air Filter Replaced"
                        },
                        new
                        {
                            Id = 7002,
                            Category = "HVAC",
                            Name = "AC System Inspected"
                        },
                        new
                        {
                            Id = 7003,
                            Category = "HVAC",
                            Name = "AC Refrigerant Recharged"
                        },
                        new
                        {
                            Id = 7004,
                            Category = "HVAC",
                            Name = "AC Leak Repaired"
                        },
                        new
                        {
                            Id = 7005,
                            Category = "HVAC",
                            Name = "AC Compressor Replaced"
                        },
                        new
                        {
                            Id = 7006,
                            Category = "HVAC",
                            Name = "AC Condenser Replaced"
                        },
                        new
                        {
                            Id = 7007,
                            Category = "HVAC",
                            Name = "AC Evaporator Replaced"
                        },
                        new
                        {
                            Id = 7008,
                            Category = "HVAC",
                            Name = "Heater System Inspected"
                        },
                        new
                        {
                            Id = 7009,
                            Category = "HVAC",
                            Name = "Heater Core Replaced"
                        },
                        new
                        {
                            Id = 7010,
                            Category = "HVAC",
                            Name = "Blower Motor Replaced"
                        },
                        new
                        {
                            Id = 7011,
                            Category = "HVAC",
                            Name = "Climate Control Repaired"
                        },
                        new
                        {
                            Id = 9000,
                            Category = "Powertrain",
                            Name = "Oil & Filter Changed"
                        },
                        new
                        {
                            Id = 9001,
                            Category = "Powertrain",
                            Name = "Engine Inspected"
                        },
                        new
                        {
                            Id = 9002,
                            Category = "Powertrain",
                            Name = "Engine Tuned Up"
                        },
                        new
                        {
                            Id = 9003,
                            Category = "Powertrain",
                            Name = "Spark Plugs Replaced"
                        },
                        new
                        {
                            Id = 9004,
                            Category = "Powertrain",
                            Name = "Ignition Coils Replaced"
                        },
                        new
                        {
                            Id = 9005,
                            Category = "Powertrain",
                            Name = "Engine Air Filter Replaced"
                        },
                        new
                        {
                            Id = 9006,
                            Category = "Powertrain",
                            Name = "Fuel Filter Replaced"
                        },
                        new
                        {
                            Id = 9007,
                            Category = "Powertrain",
                            Name = "Fuel Injectors Cleaned"
                        },
                        new
                        {
                            Id = 9008,
                            Category = "Powertrain",
                            Name = "Fuel Injectors Replaced"
                        },
                        new
                        {
                            Id = 9009,
                            Category = "Powertrain",
                            Name = "Throttle Body Cleaned"
                        },
                        new
                        {
                            Id = 9010,
                            Category = "Powertrain",
                            Name = "Fuel Pump Replaced"
                        },
                        new
                        {
                            Id = 9011,
                            Category = "Powertrain",
                            Name = "Coolant Flushed"
                        },
                        new
                        {
                            Id = 9012,
                            Category = "Powertrain",
                            Name = "Coolant Replaced"
                        },
                        new
                        {
                            Id = 9013,
                            Category = "Powertrain",
                            Name = "Thermostat Replaced"
                        },
                        new
                        {
                            Id = 9014,
                            Category = "Powertrain",
                            Name = "Water Pump Replaced"
                        },
                        new
                        {
                            Id = 9015,
                            Category = "Powertrain",
                            Name = "Timing Belt Replaced"
                        },
                        new
                        {
                            Id = 9016,
                            Category = "Powertrain",
                            Name = "Timing Chain Serviced"
                        },
                        new
                        {
                            Id = 9017,
                            Category = "Powertrain",
                            Name = "Serpentine Belt Replaced"
                        },
                        new
                        {
                            Id = 9018,
                            Category = "Powertrain",
                            Name = "Engine Mounts Replaced"
                        },
                        new
                        {
                            Id = 9019,
                            Category = "Powertrain",
                            Name = "Engine Leak Repaired"
                        },
                        new
                        {
                            Id = 9020,
                            Category = "Powertrain",
                            Name = "Transmission Fluid Serviced"
                        },
                        new
                        {
                            Id = 9021,
                            Category = "Powertrain",
                            Name = "Transmission Filter Replaced"
                        },
                        new
                        {
                            Id = 9022,
                            Category = "Powertrain",
                            Name = "Transmission Flushed"
                        },
                        new
                        {
                            Id = 9023,
                            Category = "Powertrain",
                            Name = "Transmission Repaired"
                        },
                        new
                        {
                            Id = 9024,
                            Category = "Powertrain",
                            Name = "Transmission Replaced"
                        },
                        new
                        {
                            Id = 9025,
                            Category = "Powertrain",
                            Name = "Clutch Replaced"
                        },
                        new
                        {
                            Id = 9026,
                            Category = "Powertrain",
                            Name = "Differential Fluid Serviced"
                        },
                        new
                        {
                            Id = 9027,
                            Category = "Powertrain",
                            Name = "Transfer Case Serviced"
                        },
                        new
                        {
                            Id = 9028,
                            Category = "Powertrain",
                            Name = "Front CV Axles Replaced"
                        },
                        new
                        {
                            Id = 9029,
                            Category = "Powertrain",
                            Name = "Rear CV Axles Replaced"
                        },
                        new
                        {
                            Id = 9030,
                            Category = "Powertrain",
                            Name = "Front CV Boots Replaced"
                        },
                        new
                        {
                            Id = 9031,
                            Category = "Powertrain",
                            Name = "Rear CV Boots Replaced"
                        },
                        new
                        {
                            Id = 11000,
                            Category = "Safety",
                            Name = "Safety Inspection Completed"
                        },
                        new
                        {
                            Id = 11001,
                            Category = "Safety",
                            Name = "Airbag System Inspected"
                        },
                        new
                        {
                            Id = 11002,
                            Category = "Safety",
                            Name = "Front Airbags Replaced"
                        },
                        new
                        {
                            Id = 11003,
                            Category = "Safety",
                            Name = "Side Airbags Replaced"
                        },
                        new
                        {
                            Id = 11004,
                            Category = "Safety",
                            Name = "Seat Belts Inspected"
                        },
                        new
                        {
                            Id = 11005,
                            Category = "Safety",
                            Name = "Front Seat Belts Replaced"
                        },
                        new
                        {
                            Id = 11006,
                            Category = "Safety",
                            Name = "Rear Seat Belts Replaced"
                        },
                        new
                        {
                            Id = 11007,
                            Category = "Safety",
                            Name = "ADAS Calibrated"
                        },
                        new
                        {
                            Id = 11008,
                            Category = "Safety",
                            Name = "Front Camera Calibrated"
                        },
                        new
                        {
                            Id = 11009,
                            Category = "Safety",
                            Name = "Rear Camera Calibrated"
                        },
                        new
                        {
                            Id = 11010,
                            Category = "Safety",
                            Name = "Radar Sensor Calibrated"
                        },
                        new
                        {
                            Id = 11011,
                            Category = "Safety",
                            Name = "Driver Assistance System Inspected"
                        },
                        new
                        {
                            Id = 11012,
                            Category = "Safety",
                            Name = "Recall Inspected"
                        },
                        new
                        {
                            Id = 11013,
                            Category = "Safety",
                            Name = "Recall Repair Completed"
                        },
                        new
                        {
                            Id = 13000,
                            Category = "Steering",
                            Name = "Steering System Inspected"
                        },
                        new
                        {
                            Id = 13001,
                            Category = "Steering",
                            Name = "Power Steering Fluid Serviced"
                        },
                        new
                        {
                            Id = 13002,
                            Category = "Steering",
                            Name = "Power Steering Flushed"
                        },
                        new
                        {
                            Id = 13003,
                            Category = "Steering",
                            Name = "Steering Rack Replaced"
                        },
                        new
                        {
                            Id = 13004,
                            Category = "Steering",
                            Name = "Steering Gear Repaired"
                        },
                        new
                        {
                            Id = 13005,
                            Category = "Steering",
                            Name = "Front Tie Rods Replaced"
                        },
                        new
                        {
                            Id = 13006,
                            Category = "Steering",
                            Name = "Front Tie Rod Ends Replaced"
                        },
                        new
                        {
                            Id = 13007,
                            Category = "Steering",
                            Name = "Steering Linkage Repaired"
                        },
                        new
                        {
                            Id = 13008,
                            Category = "Steering",
                            Name = "Steering Column Repaired"
                        },
                        new
                        {
                            Id = 13009,
                            Category = "Steering",
                            Name = "Electric Power Steering Diagnosed"
                        },
                        new
                        {
                            Id = 15000,
                            Category = "Suspension",
                            Name = "Suspension System Inspected"
                        },
                        new
                        {
                            Id = 15001,
                            Category = "Suspension",
                            Name = "Front Shock Absorbers Replaced"
                        },
                        new
                        {
                            Id = 15002,
                            Category = "Suspension",
                            Name = "Rear Shock Absorbers Replaced"
                        },
                        new
                        {
                            Id = 15003,
                            Category = "Suspension",
                            Name = "Front Struts Replaced"
                        },
                        new
                        {
                            Id = 15004,
                            Category = "Suspension",
                            Name = "Rear Struts Replaced"
                        },
                        new
                        {
                            Id = 15005,
                            Category = "Suspension",
                            Name = "Front Coil Springs Replaced"
                        },
                        new
                        {
                            Id = 15006,
                            Category = "Suspension",
                            Name = "Rear Coil Springs Replaced"
                        },
                        new
                        {
                            Id = 15007,
                            Category = "Suspension",
                            Name = "Air Suspension Serviced"
                        },
                        new
                        {
                            Id = 15008,
                            Category = "Suspension",
                            Name = "Air Suspension Compressor Replaced"
                        },
                        new
                        {
                            Id = 15009,
                            Category = "Suspension",
                            Name = "Front Control Arms Replaced"
                        },
                        new
                        {
                            Id = 15010,
                            Category = "Suspension",
                            Name = "Rear Control Arms Replaced"
                        },
                        new
                        {
                            Id = 15011,
                            Category = "Suspension",
                            Name = "Front Ball Joints Replaced"
                        },
                        new
                        {
                            Id = 15012,
                            Category = "Suspension",
                            Name = "Rear Ball Joints Replaced"
                        },
                        new
                        {
                            Id = 15013,
                            Category = "Suspension",
                            Name = "Front Bushings Replaced"
                        },
                        new
                        {
                            Id = 15014,
                            Category = "Suspension",
                            Name = "Rear Bushings Replaced"
                        },
                        new
                        {
                            Id = 15015,
                            Category = "Suspension",
                            Name = "Front Sway Bar Links Replaced"
                        },
                        new
                        {
                            Id = 15016,
                            Category = "Suspension",
                            Name = "Rear Sway Bar Links Replaced"
                        },
                        new
                        {
                            Id = 15017,
                            Category = "Suspension",
                            Name = "Front Sway Bar Bushings Replaced"
                        },
                        new
                        {
                            Id = 15018,
                            Category = "Suspension",
                            Name = "Rear Sway Bar Bushings Replaced"
                        },
                        new
                        {
                            Id = 15019,
                            Category = "Suspension",
                            Name = "Wheel Alignment Completed"
                        },
                        new
                        {
                            Id = 15020,
                            Category = "Suspension",
                            Name = "Ride Height Adjusted"
                        },
                        new
                        {
                            Id = 17000,
                            Category = "Tires & Wheels",
                            Name = "Tires Inspected"
                        },
                        new
                        {
                            Id = 17001,
                            Category = "Tires & Wheels",
                            Name = "Front Tires Inspected"
                        },
                        new
                        {
                            Id = 17002,
                            Category = "Tires & Wheels",
                            Name = "Rear Tires Inspected"
                        },
                        new
                        {
                            Id = 17003,
                            Category = "Tires & Wheels",
                            Name = "Tires Rotated"
                        },
                        new
                        {
                            Id = 17004,
                            Category = "Tires & Wheels",
                            Name = "Front Tires Replaced"
                        },
                        new
                        {
                            Id = 17005,
                            Category = "Tires & Wheels",
                            Name = "Rear Tires Replaced"
                        },
                        new
                        {
                            Id = 17006,
                            Category = "Tires & Wheels",
                            Name = "Tire Repaired"
                        },
                        new
                        {
                            Id = 17007,
                            Category = "Tires & Wheels",
                            Name = "Tires Balanced"
                        },
                        new
                        {
                            Id = 17008,
                            Category = "Tires & Wheels",
                            Name = "Tire Pressure Adjusted"
                        },
                        new
                        {
                            Id = 17009,
                            Category = "Tires & Wheels",
                            Name = "TPMS Inspected"
                        },
                        new
                        {
                            Id = 17010,
                            Category = "Tires & Wheels",
                            Name = "Front TPMS Sensor Replaced"
                        },
                        new
                        {
                            Id = 17011,
                            Category = "Tires & Wheels",
                            Name = "Rear TPMS Sensor Replaced"
                        },
                        new
                        {
                            Id = 17012,
                            Category = "Tires & Wheels",
                            Name = "Wheels Inspected"
                        },
                        new
                        {
                            Id = 17013,
                            Category = "Tires & Wheels",
                            Name = "Front Wheels Replaced"
                        },
                        new
                        {
                            Id = 17014,
                            Category = "Tires & Wheels",
                            Name = "Rear Wheels Replaced"
                        },
                        new
                        {
                            Id = 17015,
                            Category = "Tires & Wheels",
                            Name = "Wheels Repaired"
                        },
                        new
                        {
                            Id = 17016,
                            Category = "Tires & Wheels",
                            Name = "Lug Nuts Replaced"
                        },
                        new
                        {
                            Id = 17017,
                            Category = "Tires & Wheels",
                            Name = "Seasonal Tires Changed"
                        },
                        new
                        {
                            Id = 99999,
                            Category = "Other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("GarageLog.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_vehicles_user_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("GarageLog.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("GarageLog.Core.Entities.ServiceRecord", b =>
                {
                    b.HasOne("GarageLog.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_records_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GarageLog.Core.Entities.ServiceRecordItem", b =>
                {
                    b.HasOne("GarageLog.Core.Entities.ServiceRecord", "ServiceRecord")
                        .WithMany("Items")
                        .HasForeignKey("ServiceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_record_items_service_records_service_record_id");

                    b.HasOne("GarageLog.Core.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceRecordItems")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_record_items_service_types_service_type_id");

                    b.Navigation("ServiceRecord");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("GarageLog.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("GarageLog.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GarageLog.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GarageLog.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("GarageLog.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GarageLog.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("GarageLog.Core.Entities.ServiceRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GarageLog.Core.Entities.ServiceType", b =>
                {
                    b.Navigation("ServiceRecordItems");
                });

            modelBuilder.Entity("GarageLog.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("ServiceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
